apiVersion: v1
kind: Template
metadata:
  name: graph-refresh-imagestream
  annotations:
    description: >
      This is Thoth Graph Refresh CronJob ImageStream, this template is meant to be used by Bots,
      but could also be used by humans...
    openshift.io/display-name: "Thoth: Graph Refresh Job ImageStream"
    version: 0.6.0
    tags: thoth,graph-refresh,ai-stacks,aistacks,graph
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Graph Refresh Job ImageStream to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: graph-refresh-imagestream
    thoth: 0.1.0
    app: thoth
    component: graph-refresh

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      labels:
        app: thoth
        component: graph-refresh
      name: graph-refresh-job
    spec:
      name: latest
      lookupPolicy:
        local: true
